[theme]
base="dark"
primaryColor="#0d6efd"
backgroundColor="#0a0a23"
secondaryBackgroundColor="#131327"
textColor="#e0e0e0"
font="sans serif"

[server]
headless = true
enableCORS = false

[ui]
hideMenu = true
hideFooter = true
